export const API_END_POINTS = {
  DOCTORS_LIST: "user/doctors/list",
  WEEKDAY_LIST: "user/slots/weekdaylist",
  LOGIN: "user/login",
  USER_DETAILS: "user/details",
  DOCTOR_SLOTS: "user/slots",
  CREATE_APPOINTMENT: "user/appointment/create",
  APPOINTMENT_LIST: "user/appointment/list",
  MEDICATIONS: "user/prescription/daywise/details",
  APPOINTMENT_HISTORY: "user/appointment/history/list",
  UPDATE_MEDICATION_TAKEN: "user/prescription/medication/status/update",
  UPLOAD_DOCUMENTS: "common/customer/upload/records",
  APPOINTMENT_DETAILS: "user/appointment/details",
  UPLOAD_PROFiLE_PICTURE: "common/customer/upload/profilepicture",
  REGISTER: "/user/signup",
  SUBMIT_FEEDBACK: "user/appointment/feedback",
  AILMENT_LIST: "user/ailment/list",
  REPORT_TYPE_LIST: "user/documenttype/list",
  UPDATE_APPOINTMENT:"user/appointment/update",
  UPDATE_PROFILE:"user/profile/details/update"
};
